//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePostOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_branch
    {
        public int id { get; set; }
        public string branch_code { get; set; }
        public string branch_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<int> city_id { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> user_id { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
    }
}
